name: Generated APK AAB (Upload - Create Artifact To Github Action)

env:
  # The name of the main module repository
  main_project_module: app

  # The name of the Play Store
  playstore_name: webtv

on:

  push:
    branches:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '23'

      # Setup Yarn
      - name: Setup yarn
        run: npm install -g yarn

      # Install Dependencies
      - name: Install dependencies
        run: yarn install

      # Set Current Date As Env Variable
      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      # Set Repository Name As Env Variable
      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '17'
          cache: 'gradle'

      - name: Change wrapper permissions
        working-directory: android
        run: chmod +x ./gradlew

      # Create APK Release
      - name: Build apk release project (APK) - ${{ env.main_project_module }} module
        working-directory: android
        run: ./gradlew assembleRelease -PreactNativeArchitectures=arm64-v8a

      # Noted For Output [main_project_module]/build/outputs/apk/release/
      - name: Upload APK Release - ${{ env.repository_name }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.date_today }} - ${{ env.playstore_name }} - ${{ env.repository_name }} - APK(s) release generated
          path: android/${{ env.main_project_module }}/build/outputs/apk/release/

      - name: Build ota files
        run: |
          mkdir ota
          echo "{\"name\": \"webtv-ota\", \"version\": \"0.0.$(date +'%Y%m%d%H%M%S')\", \"files\": [\"update.json\", \"index.android.bundle.zip\"]}" > ./ota/package.json
          yarn export-android
      - name: NPM publish
        working-directory: ota
        run: |
          npm set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}